name: "Unit Tests"

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        dependencies:
          - "--prefer-lowest"
          - ""
        php-version:
          - "8.0"
          - "7.4"
          - "7.3"
        composer:
          - "v2"
        include:
          - php-version: "7.3"
            composer: "v1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: "composer:${{ matrix.composer }}"
      - name: "Install dependencies"
        run: "composer update ${{ matrix.dependencies }} --no-interaction"
      - name: "Run tests"
        run: "vendor/bin/phpunit"
